data:
  data_root: /home/admin/AGML_ResearchGroup/SuperResolution
  dataset_name: m-cashew-plantation
  batch_size: 64
  crop_size: 224
  num_workers: 10
  pin_mem: true
  drop_last: true
logging:
  folder: logs/eval/m_cashew_linear_probe_lrmodel_s224_ep300_2
  write_tag: m_cashew_linear_probe_lrmodel_s224_ep300_2
meta:
  model_name: vit_small
  patch_size: 14
  load_checkpoint: false
  read_checkpoint: null
  pretrained_checkpoint: /home/admin/john/ijepa/logs/sen2venus_vits14.224-bs.128-ep.100_lr/jepa_sen2venus_lr-ep300.pth.tar
  use_bfloat16: true
  seg_n_cls: 7
  use_batchnorm: false
optimization:
  epochs: 100
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0001
  final_lr: 1.0e-06
  warmup: 10
  weight_decay: 0.0
  final_weight_decay: 0.0